/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as ThreatModelRouteImport } from './routes/threat-model'
import { Route as JoinRouteImport } from './routes/join'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as RoomSessionIdRouteImport } from './routes/room.$sessionId'
import { Route as LegalDataProcessingRouteImport } from './routes/legal/data-processing'
import { Route as LegalDpaRouteImport } from './routes/legal/dpa'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatModelRoute = ThreatModelRouteImport.update({
  id: '/threat-model',
  path: '/threat-model',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomSessionIdRoute = RoomSessionIdRouteImport.update({
  id: '/room/$sessionId',
  path: '/room/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDataProcessingRoute = LegalDataProcessingRouteImport.update({
  id: '/legal/data-processing',
  path: '/legal/data-processing',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDpaRoute = LegalDpaRouteImport.update({
  id: '/legal/dpa',
  path: '/legal/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/evaluation': typeof EvaluationRoute
  '/threat-model': typeof ThreatModelRoute
  '/join': typeof JoinRoute
  '/sessions': typeof SessionsRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/room/$sessionId': typeof RoomSessionIdRoute
  '/legal/data-processing': typeof LegalDataProcessingRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/evaluation': typeof EvaluationRoute
  '/threat-model': typeof ThreatModelRoute
  '/join': typeof JoinRoute
  '/sessions': typeof SessionsRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/room/$sessionId': typeof RoomSessionIdRoute
  '/legal/data-processing': typeof LegalDataProcessingRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/evaluation': typeof EvaluationRoute
  '/threat-model': typeof ThreatModelRoute
  '/join': typeof JoinRoute
  '/sessions': typeof SessionsRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/room/$sessionId': typeof RoomSessionIdRoute
  '/legal/data-processing': typeof LegalDataProcessingRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/docs'
    | '/evaluation'
    | '/threat-model'
    | '/join'
    | '/sessions'
    | '/sessions/$sessionId'
    | '/room/$sessionId'
    | '/legal/data-processing'
    | '/legal/dpa'
    | '/legal/privacy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/docs'
    | '/evaluation'
    | '/threat-model'
    | '/join'
    | '/sessions'
    | '/sessions/$sessionId'
    | '/room/$sessionId'
    | '/legal/data-processing'
    | '/legal/dpa'
    | '/legal/privacy'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/docs'
    | '/evaluation'
    | '/threat-model'
    | '/join'
    | '/sessions'
    | '/sessions/$sessionId'
    | '/room/$sessionId'
    | '/legal/data-processing'
    | '/legal/dpa'
    | '/legal/privacy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DocsRoute: typeof DocsRoute
  EvaluationRoute: typeof EvaluationRoute
  ThreatModelRoute: typeof ThreatModelRoute
  JoinRoute: typeof JoinRoute
  SessionsRoute: typeof SessionsRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  RoomSessionIdRoute: typeof RoomSessionIdRoute
  LegalDataProcessingRoute: typeof LegalDataProcessingRoute
  LegalDpaRoute: typeof LegalDpaRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-model': {
      id: '/threat-model'
      path: '/threat-model'
      fullPath: '/threat-model'
      preLoaderRoute: typeof ThreatModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$sessionId': {
      id: '/room/$sessionId'
      path: '/room/$sessionId'
      fullPath: '/room/$sessionId'
      preLoaderRoute: typeof RoomSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/data-processing': {
      id: '/legal/data-processing'
      path: '/legal/data-processing'
      fullPath: '/legal/data-processing'
      preLoaderRoute: typeof LegalDataProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/dpa': {
      id: '/legal/dpa'
      path: '/legal/dpa'
      fullPath: '/legal/dpa'
      preLoaderRoute: typeof LegalDpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DocsRoute: DocsRoute,
  EvaluationRoute: EvaluationRoute,
  ThreatModelRoute: ThreatModelRoute,
  JoinRoute: JoinRoute,
  SessionsRoute: SessionsRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  RoomSessionIdRoute: RoomSessionIdRoute,
  LegalDataProcessingRoute: LegalDataProcessingRoute,
  LegalDpaRoute: LegalDpaRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
